name: ChatServer
main: ChatServer.Main
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: DevilLord
description: Customize Your chat Server
website: https://github.com/DevilLordAero
commands:
hello:
description: Hello to server
usage: "/hello <Message>"
permission: chatserver.hello
permissions:
chatserver.hello:
description: "Allow the user to run commands"
default: true